### ISSUE TITLE
Support for managing already existing accounts

### ISSUE THREAD

**Issue by oravirt** [hashicorp/vault-plugin-database-oracle#32] opened 2020-02-18 09:36 UTC
This may be a duplicate of #23, but here goes anyway.

Using the plugin in its current state is hard(-er) if you haven't already made the separation of an application into a schema `owner` and an application `user`, where the `owner` owns all objects (tables, packages etc) and the `user` is actually executing packages, running DML etc.
In this case the `owner` would never log in since that job is delegated to the `user` and the `user` would have all the necessary privileges to access all objects that is owned by `owner`

Retrofitting that separation is non-trivial to say the least (but this is what you have to do today if you want to use the plugin)

If you, on the other hand, allowed Vault to just manage the password rotation for the `owner`  this could pretty much be a drop-in solution...

**Comment by jefferai** [comment] 2020-02-18 15:04
As you said, duplicate of #23 . Closing in favor.

**Closed by jefferai** 2020-02-18 15:04 UTC
