### ISSUE TITLE
When I run the command "vault read database/creds/my-role", the response is "Error reading database/creds/my-role: Get http://127.0.0.1:8200/v1/database/creds/my-role: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"

### ISSUE THREAD

**Issue by 2994186010** [hashicorp/vault-plugin-database-oracle#22] opened 2019-08-01 09:26 UTC
I have successfully registered the vault-plugin-database-oracle in vault.
    My environment: the version of vault is v1.1.3 and I use the pre-built binary vault-plugin-database-oracle_0.1.5. 
    The commands that I run are as following:
    `# vault write database/config/my-oracle-database plugin_name=oracle-database-plugin connection_url="system/Admin_123@192.168.80.134:1521/orcl" allowed_roles="my-role"
    # vault write database/roles/my-role db_name=my-oracle-database creation_statements="CREATE USER {{name}} IDENTIFIED BY {{password}}; GRANT CONNECT TO {{name}}; GRANT CREATE SESSION TO {{name}};" default_ttl="60s" max_ttl="24h"vault read database/creds/my-role
    # vault read database/creds/my-role`
    When I run the command "vault read database/creds/my-role" the first few times, everything goes well. However, after the first few times, I encounter a problem, it is as stated in the title. When I run the command "vault read database/creds/my-role", the response is "Error reading database/creds/my-role: Get http://127.0.0.1:8200/v1/database/creds/my-role: net/http: request canceled (Client.Timeout exceeded while awaiting headers)".
    Then I restart the vault with the parameter "--log-level=trace". The message of the log file is as following:
    2019-08-01T18:02:49.840+0800 [TRACE] secrets.database.database_a63c0ef8.oracle-database-plugin: revoke user: transport=gRPC status=finished err="rpc error: code = DeadlineExceeded desc = context deadline exceeded" took=1m30.000991096s
2019-08-01T18:02:49.840+0800 [ERROR] expiration: failed to revoke lease: lease_id=database/creds/my-role/kr2lb47fvPbXLcOSRBdZ7niy error="failed to revoke entry: resp: (*logical.Response)(nil) err: rpc error: code = DeadlineExceeded desc = context deadline exceeded"
2019-08-01T18:02:50.589+0800 [TRACE] secrets.database.database_a63c0ef8.oracle-database-plugin: revoke user: transport=gRPC status=finished err="rpc error: code = DeadlineExceeded desc = context deadline exceeded" took=1m30.003770199s
2019-08-01T18:02:50.589+0800 [ERROR] expiration: failed to revoke lease: lease_id=database/creds/my-role/FfCikNAhf9o55piOeFzXKRgv error="failed to revoke entry: resp: (*logical.Response)(nil) err: rpc error: code = DeadlineExceeded desc = context deadline exceeded"
2019-08-01T18:03:41.548+0800 [DEBUG] rollback: attempting rollback: path=auth/token/
2019-08-01T18:03:41.548+0800 [DEBUG] rollback: attempting rollback: path=sys/
2019-08-01T18:03:41.548+0800 [DEBUG] rollback: attempting rollback: path=identity/
2019-08-01T18:03:41.548+0800 [DEBUG] rollback: attempting rollback: path=database/
2019-08-01T18:03:41.548+0800 [DEBUG] rollback: attempting rollback: path=cubbyhole/
2019-08-01T18:03:50.126+0800 [TRACE] secrets.database.database_a63c0ef8.oracle-database-plugin: create user: transport=gRPC status=started
    When I use the username and password that vault generate before the problem occurs,  I can successfully log in to the Vault. I think that when I encounter the above problem, the vault can not revoke the credentials of oracle and create user.

**Comment by michelvocks** [comment] 2019-08-01 12:15
Duplicate of https://groups.google.com/forum/#!topic/vault-tool/RvPar1uuKic

**Closed by michelvocks** 2019-08-01 12:15 UTC
